name: Auto Commit Code

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the top of every hour

jobs:
  commit-and-push:
    runs-on: ubuntu-latest  # The OS environment for running this workflow

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Perform the desired update (e.g., update a file)
      - name: Update Code
        run: |
          echo "Automated update at $(date)" >> update_log.txt

      # Step 3: Commit and Push the changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "Subhadip-Hazra"  # Your GitHub username
          git config --global user.email "subhadiphazra722@gmail.com"  # Your GitHub email
          
          # Pull the latest changes from the remote repository
          git pull https://Subhadip-Hazra:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Subhadip-Hazra/GITHUB-AUTOMATE.git main

          git add .
          git commit -m "Automated commit: $(date)" || echo "No changes to commit"  # Prevents errors if no changes
          git push https://Subhadip-Hazra:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Subhadip-Hazra/GITHUB-AUTOMATE.git || echo "Push failed"
